galacticcouncil/Basilisk-ui

src/api/addLiquidity.ts, src/api/balances.ts, src/api/transaction.ts, src/sections/pools/PoolsPage.utils.ts, src/sections/pools/header/PoolsHeader.tsx, src/sections/pools/pool/actions/PoolActions.tsx, src/sections/pools/pool/modals/addLiquidity/PoolAddLiquidity.tsx, src/sections/pools/pool/modals/joinFarm/PoolJoinFarmDeposit.tsx, src/sections/pools/pool/modals/joinFarm/PoolJoinFarmSectionList.tsx, src/sections/pools/pool/modals/removeLiquidity/PoolRemoveLiquidity.tsx, src/sections/pools/pool/position/PoolPosition.utils.ts, src/sections/pools/pool/shares/PoolShares.tsx, src/sections/transaction/ReviewTransactionForm.tsx, src/sections/wallet/connect/confirmPending/WalletConnectConfirmPending.tsx, src/sections/wallet/connect/modal/WalletConnectButton.tsx, src/sections/wallet/connect/modal/WalletConnectModal.tsx, src/state/store.ts
=> Persist account and wallet provider into localStorage

src/utils/apr.ts
multiplied APR by 100 since it should be a displayed as a percentage
=> updated APR calculation

.env.development, .env.production, .env.rococo, package.json, src/api/volume.ts, src/i18n/locales/en/translations.json, src/sections/pools/PoolsPage.tsx, src/sections/pools/pool/details/PoolDetails.tsx, src/sections/pools/pool/details/PoolDetails.utils.ts, src/utils/queryKeys.ts, yarn.lock
At the moment, we're showing the trade volume of both assets w/out converting to aUSD, as this will most likely require an update to the indexer.
=> feat(HYDRA-178): add 24h volume trade

src/utils/formatting.ts
=> Update formatting logic

src/sections/pools/PoolsPage.utils.ts
=> Fix safari infinite loading

src/utils/formatting.ts
=> Cap decimal places if expanding

src/sections/pools/pool/modals/addLiquidity/PoolAddLiquidityModal.tsx
it's better to return null than BN(0) to check if some error ocurred
=> fix: Share token tweaks

src/sections/pools/pool/modals/addLiquidity/PoolAddLiquidityModal.tsx, src/utils/constants.ts
Based on discord conversation with Juraj
=> fix: Fallback at shareToken decimals

src/components/Table/Table.styled.ts, src/components/Table/TableSkeleton.tsx, src/sections/wallet/assets/table/skeleton/WalletAssetsTableSkeleton.utils.tsx
=> Fix blocking screen in Wallet page when logged out

package.json, src/api/asset.ts, src/components/Table/Table.tsx, src/sections/trade/TradePage.tsx, src/sections/wallet/assets/table/WalletAssetsTable.utils.tsx, src/sections/wallet/assets/table/actions/WalletAssetsTableActions.tsx, src/sections/wallet/assets/table/data/WalletAssetsTableData.utils.ts, src/utils/queryKeys.ts, yarn.lock
Changes required on the trade app are not cleaned up for MR on their side yet. WIll do after some further discussion.
=> Add trade app deeplinking from wallet page

src/components/AssetSelect/AssetSelect.tsx, src/i18n/locales/en/translations.json, src/sections/pools/farm/deposit/PoolFarmDeposit.tsx, src/sections/pools/header/PoolsHeader.utils.ts, src/sections/pools/pool/modals/addLiquidity/PoolAddLiquidityModal.tsx, src/sections/transaction/ReviewTransactionForm.tsx
- fixed "Total Value in Farms" value
- added additional text below "Waiting for Signature" button (fixes #204)
- fixed asset input placeholder (fixes #196)
- fixed shares input "Max" button (fixes #199)
=> various minor fixes to pools & farms page

src/utils/farms/apr.ts
=> halved APR values

src/components/AssetInput/AssetInput.tsx, src/utils/formatting.ts
=> Added asset value formatting

src/sections/wallet/connect/accountSelect/WalletConnectAccountSelect.styled.ts, src/sections/wallet/connect/accountSelect/WalletConnectAccountSelect.tsx, src/sections/wallet/connect/accountSelect/item/WalletConnectAccountSelectItem.styled.ts
=> Fixed connect wallet modal styling

src/sections/pools/farm/claim/PoolFarmClaim.tsx, src/sections/pools/farm/modals/positionDetail/PoolFarmPositionDetail.tsx, src/sections/pools/farm/modals/positionDetail/PoolFarmPositionDetailSectionList.tsx, src/sections/pools/farm/withdraw/PoolFarmWithdraw.tsx, src/utils/farms/claiming.ts
=> feat(HYDRA-242): show only specific NFT in position detail

src/utils/farms/claiming/claimSimulator.ts
=> renamed variable

src/i18n/locales/en/translations.json, src/sections/pools/farm/loyaltyGraph/PoolFarmLoyaltyGraph.utils.ts
=> updated loyalty graph values

src/components/Layout/Header/Header.styled.ts, src/components/Layout/Page/Page.styled.ts, src/components/Modal/Modal.styled.ts, src/components/Modal/Modal.tsx, src/components/Tabs/TabLink.tsx, src/i18n/locales/en/translations.json, src/sections/wallet/assets/WalletAssetsHeader.tsx, src/sections/wallet/assets/table/WalletAssetsTable.tsx, src/sections/wallet/assets/table/WalletAssetsTable.utils.tsx, src/sections/wallet/assets/table/actions/WalletAssetsTableActions.tsx, src/sections/wallet/assets/table/actions/WalletAssetsTableActionsMob.tsx, src/sections/wallet/assets/table/data/WalletAssetsTableData.styled.ts, src/sections/wallet/assets/table/data/WalletAssetsTableData.tsx, src/sections/wallet/header/WalletHeader.tsx, src/sections/wallet/header/WalletTabs.tsx, src/sections/wallet/vesting/WalletVestingHeader.tsx
-Fixed scroll bar issue 
-Fixed navigation for Buy and Sell
-Added Actions Buttons of the Assets for the mobile view
-Fixed minor styling issues for the responsive view
=> Added Mob Actions Modal

src/api/asset.ts, src/api/assetDetails.ts, src/components/AddressInput/AddressInput.tsx, src/components/AssetSelect/AssetSelectInput.tsx, src/components/AssetSelect/LiquidityPositionInput.tsx, src/sections/assets/AssetsModalRow.tsx, src/sections/pools/farm/claim/PoolFarmClaim.tsx, src/sections/pools/farm/deposit/PoolFarmDeposit.tsx, src/sections/pools/farm/detail/PoolFarmDetail.tsx, src/sections/pools/farm/loyaltyGraph/PoolFarmLoyaltyGraph.utils.ts, src/sections/pools/farm/loyaltyGraph/PoolJoinFarmLoyaltyGraph.worker.ts, src/sections/pools/farm/position/PoolFarmPosition.tsx, src/sections/pools/pool/details/PoolDetails.tsx, src/sections/pools/pool/incentives/row/PoolIncentivesRow.tsx, src/sections/pools/pool/modals/addLiquidity/PoolAddLiquidityModal.tsx, src/sections/pools/pool/modals/addLiquidity/assetSelect/PoolAddLiquidityAssetSelect.tsx, src/sections/pools/pool/modals/myPositions/MyPositionsHeader.tsx, src/sections/pools/pool/modals/removeLiquidity/PoolRemoveLiquidity.tsx, src/sections/pools/pool/modals/removeLiquidity/reward/PoolRemoveLiquidityReward.tsx, src/sections/pools/pool/position/farm/PoolPositionFarmRedeposit.tsx, src/sections/wallet/assets/WalletAssets.tsx, src/sections/wallet/assets/table/WalletLiquidityPositionsTable.utils.tsx, src/sections/wallet/assets/table/actions/WalletLiquidityPositionsTableActionsMob.tsx, src/sections/wallet/assets/table/data/WalletAssetsTableData.utils.ts, src/sections/wallet/assets/table/data/WalletLiquidityPositionsData.tsx, src/sections/wallet/assets/table/data/WalletLiquidityPositionsData.utils.ts, src/sections/wallet/transfer/WalletTransferAssetSelect.tsx
-Fixed Loyalty graph performance by reducing number of points
-Fixed assets names. Now we use it from assetRegistry, instead of hard-coded
-Fixed limit for the deposited tokens
=> Fixed Asset names

src/utils/formatting.ts
=> Dollar value should at least have 2 decimal places

src/sections/pools/pool/footer/PoolFooter.tsx, src/sections/pools/pool/footer/PoolFooter.utils.ts
=> Add amount available for farms in pool footer

src/sections/pools/pool/modals/addLiquidity/PoolAddLiquidityModal.tsx, src/sections/pools/pool/modals/removeLiquidity/PoolRemoveLiquidity.tsx
=> Fixed Add/Remove liquidity fee value

src/i18n/locales/en/translations.json, src/sections/pools/PoolsPage.utils.ts, src/sections/wallet/assets/WalletAssets.tsx, src/sections/wallet/assets/WalletAssetsHeader.tsx
Fixes #298 
- Added sorting of pools based on the total usd value
=> Added Total in Pools

src/sections/pools/pool/Pool.styled.ts, src/sections/pools/pool/Pool.tsx, src/sections/pools/pool/actions/PoolActions.tsx, src/sections/pools/pool/details/PoolDetails.tsx, src/sections/pools/pool/details/PoolDetailsTradeFee.tsx, src/sections/pools/pool/details/PoolValue.tsx, src/sections/pools/pool/incentives/PoolIncentives.tsx, src/sections/pools/pool/incentives/row/MultiplePoolIncentivesRow/MultiplePoolIncentivesRow.tsx
=> fix(HYDRA-376): add tablet layout

src/sections/pools/pool/actions/PoolActions.tsx, src/sections/pools/pool/modals/myPositions/MyPositionsHeader.tsx, src/sections/pools/pool/modals/myPositions/MyPositionsModal.tsx
- Hide Claim button if there are no deposit positions
=> Disable Join Farm button

src/sections/wallet/connect/accountSelect/WalletConnectAccountSelect.tsx, src/sections/wallet/connect/modal/WalletConnectButton.tsx
- An active account should be at the top of list
- Basilisk address should be displayed as a selected address
=> Sorted selected account

src/assets/icons/Unknown.svg, src/components/Toast/ToastContent.tsx, src/i18n/locales/en/translations.json, src/sections/transaction/ReviewTransaction.utils.ts, src/sections/transaction/ReviewTransactionToast.tsx, src/state/toasts.ts
Fixes https://github.com/galacticcouncil/Basilisk-ui/issues/332
=> Added Unknown toast type

src/sections/wallet/header/WalletHeader.tsx, src/sections/wallet/vesting/WalletVestingHeader.styled.ts, src/sections/wallet/vesting/WalletVestingHeader.tsx, src/sections/wallet/vesting/WalletVestingSchedule.styled.ts, src/sections/wallet/vesting/WalletVestingSchedule.tsx
=> Fix Vesting styling

src/components/Modal/Modal.styled.ts, src/sections/wallet/connect/accountSelect/WalletConnectAccountSelect.styled.ts
=> Updated modal height

src/api/chain.ts, src/api/provider.ts, src/api/volume.ts, src/components/AppProviders/AppProviders.tsx, src/components/InfoTooltip/InfoTooltip.tsx, src/components/Layout/Page/Page.tsx, src/components/Modal/Modal.styled.ts, src/components/Modal/Modal.tsx, src/i18n/locales/en/translations.json, src/sections/gcapps/trade/TradePage.tsx, src/sections/provider/ProviderSelectModal.styled.ts, src/sections/provider/ProviderSelectModal.tsx, src/sections/provider/ProviderStatus.tsx
=> Implemented RPC Switcher

src/components/Spinner/Spinner.styled.ts
=> Changed spinner rotate direction

src/components/AddressInput/AddressInput.styled.ts, src/components/AddressInput/AddressInput.tsx, src/sections/wallet/connect/accountSelect/item/address/WalletConnectAccountSelectAddress.tsx
=> fixed minor styling issues on small devices

src/i18n/locales/en/translations.json, src/sections/pools/farm/deposit/PoolFarmDeposit.tsx, src/sections/pools/farm/detail/PoolFarmDetail.tsx, src/sections/pools/farm/modals/join/PoolFarmJoinSectionList.tsx, src/sections/pools/pool/actions/PoolActions.utils.ts, src/sections/pools/pool/actions/buttons/PoolActionsButtons.tsx
=> Enable Farm Details button

.env.development, .env.rococo, src/api/provider.ts, src/api/volume.ts, src/sections/provider/ProviderStatus.tsx, src/sections/provider/components/ProviderItem/ProviderItem.tsx, src/sections/provider/components/ProviderSelectButton/ProviderSelectButton.tsx
Display parachain block number instead of relaychain
Updated rpc url
=> Update rpc switcher
